export const BANGLADESH_DISTRICTS = [
  "Bagerhat",
  "Bandarban",
  "Barguna",
  "Barishal",
  "Bhola",
  "Bogura",
  "Brahmanbaria",
  "Chandpur",
  "Chapai Nawabganj",
  "Chattogram",
  "Chuadanga",
  "Cox's Bazar",
  "Cumilla",
  "Dhaka",
  "Dinajpur",
  "Faridpur",
  "Feni",
  "Gaibandha",
  "Gazipur",
  "Gopalganj",
  "Habiganj",
  "Jamalpur",
  "Jashore",
  "Jhalokathi",
  "Jhenaidah",
  "Joypurhat",
  "Khagrachhari",
  "Khulna",
  "Kishoreganj",
  "Kurigram",
  "Kushtia",
  "Lakshmipur",
  "Lalmonirhat",
  "Madaripur",
  "Magura",
  "Manikganj",
  "Meherpur",
  "Moulvibazar",
  "Munshiganj",
  "Mymensingh",
  "Naogaon",
  "Narail",
  "Narayanganj",
  "Narsingdi",
  "Natore",
  "Netrokona",
  "Nilphamari",
  "Noakhali",
  "Pabna",
  "Panchagarh",
  "Patuakhali",
  "Pirojpur",
  "Rajbari",
  "Rajshahi",
  "Rangamati",
  "Rangpur",
  "Satkhira",
  "Shariatpur",
  "Sherpur",
  "Sirajganj",
  "Sunamganj",
  "Sylhet",
  "Tangail",
  "Thakurgaon",
] as const;

export const SAMPLE_GEOGRAPHY = [
  {
    district: "Dhaka",
    districtCode: "BD-DHK-DHA",
    upazila: { name: "Savar", code: "BD-DHK-SAV" },
    union: { name: "Ashulia", type: "union", code: "BD-DHK-SAV-ASH" },
    mouza: { name: "Baipail", jlNumber: "JL-1042" },
  },
  {
    district: "Dhaka",
    districtCode: "BD-DHK-DHA",
    upazila: { name: "Gulshan", code: "BD-DHK-GUL" },
    union: { name: "Meradia", type: "union", code: "BD-DHK-GUL-MER" },
    mouza: { name: "Uttar Meradia", jlNumber: "JL-2785" },
  },
  {
    district: "Chattogram",
    districtCode: "BD-CTG-CTG",
    upazila: { name: "Sitakunda", code: "BD-CTG-SIT" },
    union: { name: "Sonaichhari", type: "union", code: "BD-CTG-SIT-SON" },
    mouza: { name: "Kumira", jlNumber: "JL-1801" },
  },
  {
    district: "Rajshahi",
    districtCode: "BD-RAJ-RAJ",
    upazila: { name: "Paba", code: "BD-RAJ-PAB" },
    union: { name: "Harian", type: "union", code: "BD-RAJ-PAB-HAR" },
    mouza: { name: "Harian", jlNumber: "JL-2205" },
  },
  {
    district: "Khulna",
    districtCode: "BD-KHU-KHU",
    upazila: { name: "Dumuria", code: "BD-KHU-DUM" },
    union: { name: "Maguraghona", type: "union", code: "BD-KHU-DUM-MAG" },
    mouza: { name: "Maguraghona", jlNumber: "JL-3304" },
  },
  {
    district: "Barishal",
    districtCode: "BD-BAR-BAR",
    upazila: { name: "Bakerganj", code: "BD-BAR-BAK" },
    union: { name: "Charadi", type: "union", code: "BD-BAR-BAK-CHA" },
    mouza: { name: "Charadi", jlNumber: "JL-4107" },
  },
  {
    district: "Sylhet",
    districtCode: "BD-SYL-SYL",
    upazila: { name: "Sylhet Sadar", code: "BD-SYL-SAD" },
    union: { name: "Tuker Bazar", type: "union", code: "BD-SYL-SAD-TUK" },
    mouza: { name: "Tukergaon", jlNumber: "JL-5202" },
  },
  {
    district: "Rangpur",
    districtCode: "BD-RAN-RAN",
    upazila: { name: "Rangpur Sadar", code: "BD-RAN-SAD" },
    union: { name: "Haragachh", type: "municipality", code: "BD-RAN-SAD-HAR" },
    mouza: { name: "Haragachh", jlNumber: "JL-6109" },
  },
  {
    district: "Mymensingh",
    districtCode: "BD-MYM-MYM",
    upazila: { name: "Trishal", code: "BD-MYM-TRI" },
    union: { name: "Trishal", type: "municipality", code: "BD-MYM-TRI-TRI" },
    mouza: { name: "Trishal", jlNumber: "JL-7103" },
  },
] as const;

export function districtCodeFromName(name: string) {
  return `BD-DIST-${name
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .toUpperCase()}`;
}
